# total_marks = 0
# marks = [] 
# stud_inf = []
# number_students = int(input("enter the total number of students "))
# for n in range(number_students):
#     name = input("enter the name of the student ")
#     mark = int(input("enter the score of the student "))
#     if 0 <= mark <= 100:
#         stud_inf.append((name,mark))
#         marks.append(mark)    
#         total_marks += mark
#     else:
#         print("score must be between 0 and 100")    
# if len(marks) == 0:
#     print("No valid data entered!!!")
#     exit() 
     
# lowest_mark = min(marks)
# highest_mark = max(marks)    
          
# average = total_marks / len(marks)
# print("\n----------RESULTS----------")
# print(f"Highest_mark is:     {highest_mark}")
# print(f"Lowest_mark is:     {lowest_mark}")  
# print(f"The average score is: {average:.2f}")  
# print("-"*28) 
# print(F"{'NAME':<10}{'SCORE':>16}") 
# for name,score in stud_inf:
#     print(f"{name:<10}{score:>16}")
# print("-"*25)
# print(f"{'HAVE A NICE JOB':^28}\n")

###The remaining jobs is to add a 
##Add grade
##sort students by score 
##show three top students    
 
     
    